# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'UiFile/MainFrame.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 480)
        MainWindow.setStyleSheet("background-color: rgb(227, 227, 227);")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.widget = QtWidgets.QWidget(self.centralwidget)
        self.widget.setMinimumSize(QtCore.QSize(300, 462))
        self.widget.setMaximumSize(QtCore.QSize(300, 16777215))
        self.widget.setObjectName("widget")
        self.label_9 = QtWidgets.QLabel(self.widget)
        self.label_9.setGeometry(QtCore.QRect(0, 0, 300, 140))
        self.label_9.setStyleSheet("background-color: rgb(192, 32, 52 );\n"
"border-radius:20px;")
        self.label_9.setText("")
        self.label_9.setObjectName("label_9")
        self.main_frame_3 = QtWidgets.QLabel(self.widget)
        self.main_frame_3.setGeometry(QtCore.QRect(0, 60, 300, 251))
        self.main_frame_3.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"background-color: rgb(186, 189, 182);\n"
"border-radius: 20px")
        self.main_frame_3.setText("")
        self.main_frame_3.setObjectName("main_frame_3")
        self.building = QtWidgets.QPushButton(self.widget)
        self.building.setGeometry(QtCore.QRect(70, 15, 160, 30))
        font = QtGui.QFont()
        font.setFamily("DejaVu Sans")
        font.setPointSize(15)
        font.setBold(True)
        font.setUnderline(True)
        font.setWeight(75)
        self.building.setFont(font)
        self.building.setStyleSheet("background-color: rgb(192, 32, 52);color: rgb(255, 255, 255);\n"
"border-radius: 10px;")
        self.building.setObjectName("building")
        self.QR = QtWidgets.QLabel(self.widget)
        self.QR.setEnabled(False)
        self.QR.setGeometry(QtCore.QRect(0, 65, 300, 395))
        self.QR.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"image: url(:/newPrefix/frame.png);\n"
"color: rgb(255, 255, 255);\n"
"border-radius: 20px;")
        self.QR.setObjectName("QR")
        self.label_9.raise_()
        self.building.raise_()
        self.main_frame_3.raise_()
        self.QR.raise_()
        self.gridLayout.addWidget(self.widget, 0, 0, 1, 1)
        self.widget_2 = QtWidgets.QWidget(self.centralwidget)
        self.widget_2.setMinimumSize(QtCore.QSize(475, 462))
        self.widget_2.setMaximumSize(QtCore.QSize(475, 16777215))
        self.widget_2.setObjectName("widget_2")
        self.label_10 = QtWidgets.QLabel(self.widget_2)
        self.label_10.setGeometry(QtCore.QRect(0, 0, 475, 140))
        self.label_10.setStyleSheet("background-color: rgb(192, 32, 52 );\n"
"border-radius:20px;")
        self.label_10.setText("")
        self.label_10.setObjectName("label_10")
        self.main_frame = QtWidgets.QLabel(self.widget_2)
        self.main_frame.setGeometry(QtCore.QRect(0, 65, 475, 395))
        self.main_frame.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border-radius: 20px")
        self.main_frame.setText("")
        self.main_frame.setObjectName("main_frame")
        self.main_frame_2 = QtWidgets.QLabel(self.widget_2)
        self.main_frame_2.setGeometry(QtCore.QRect(0, 60, 475, 251))
        self.main_frame_2.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"background-color: rgb(186, 189, 182);\n"
"border-radius: 20px")
        self.main_frame_2.setText("")
        self.main_frame_2.setObjectName("main_frame_2")
        self.date = QtWidgets.QLabel(self.widget_2)
        self.date.setGeometry(QtCore.QRect(30, 105, 191, 20))
        font = QtGui.QFont()
        font.setFamily("DejaVu Sans")
        font.setPointSize(9)
        font.setItalic(False)
        self.date.setFont(font)
        self.date.setStyleSheet("border-radius:10px;\n"
"background-color: rgb(255, 255, 255);\n"
"color: rgb(85, 87, 83);")
        self.date.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.date.setObjectName("date")
        self.pushButton = QtWidgets.QPushButton(self.widget_2)
        self.pushButton.setGeometry(QtCore.QRect(180, 430, 125, 20))
        self.pushButton.setStyleSheet("image: url(:/newPrefix/HUST.png);\n"
"background-color: rgb(255, 255, 255);\n"
"border-radius:0px;")
        self.pushButton.setText("")
        self.pushButton.setObjectName("pushButton")
        self.label_11 = QtWidgets.QLabel(self.widget_2)
        self.label_11.setGeometry(QtCore.QRect(235, 10, 230, 30))
        font = QtGui.QFont()
        font.setFamily("DejaVu Sans Condensed")
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.label_11.setFont(font)
        self.label_11.setStyleSheet("background-color: rgb(192, 32, 52);color: rgb(255, 255, 255);")
        self.label_11.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_11.setObjectName("label_11")
        self.label_12 = QtWidgets.QLabel(self.widget_2)
        self.label_12.setGeometry(QtCore.QRect(210, 20, 20, 23))
        self.label_12.setStyleSheet("background-color: rgb(192, 32, 52);image: url(:/newPrefix/logoHUST.png);")
        self.label_12.setText("")
        self.label_12.setObjectName("label_12")
        self.label_13 = QtWidgets.QLabel(self.widget_2)
        self.label_13.setGeometry(QtCore.QRect(235, 30, 230, 20))
        font = QtGui.QFont()
        font.setFamily("DejaVu Sans Condensed")
        font.setPointSize(7)
        self.label_13.setFont(font)
        self.label_13.setStyleSheet("background-color: rgb(192, 32, 52);color: rgb(255, 255, 255);")
        self.label_13.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_13.setObjectName("label_13")
        self.label = QtWidgets.QLabel(self.widget_2)
        self.label.setGeometry(QtCore.QRect(15, 100, 445, 331))
        self.label.setStyleSheet("image: url(:/newPrefix/animation.gif);\n"
"background-color: rgb(255, 255, 255);\n"
"border-radius: 15px;")
        self.label.setText("")
        self.label.setObjectName("label")
        self.success = QtWidgets.QWidget(self.widget_2)
        self.success.setGeometry(QtCore.QRect(40, 230, 390, 80))
        self.success.setMinimumSize(QtCore.QSize(0, 80))
        self.success.setMaximumSize(QtCore.QSize(450, 80))
        self.success.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.success.setObjectName("success")
        self.label_2 = QtWidgets.QLabel(self.success)
        self.label_2.setGeometry(QtCore.QRect(0, 0, 390, 81))
        self.label_2.setStyleSheet("border-radius:30px;\n"
"background-color: rgb(230, 255, 221);\n"
"border:5px solid rgb(255, 255, 255);")
        self.label_2.setText("")
        self.label_2.setObjectName("label_2")
        self.label_4 = QtWidgets.QLabel(self.success)
        self.label_4.setGeometry(QtCore.QRect(90, 15, 281, 51))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setStyleSheet("color: rgb(70, 195, 62);\n"
"background-color: rgb(230, 255, 221);")
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName("label_4")
        self.label_3 = QtWidgets.QLabel(self.success)
        self.label_3.setGeometry(QtCore.QRect(30, 15, 51, 51))
        self.label_3.setMaximumSize(QtCore.QSize(80, 16777215))
        self.label_3.setStyleSheet("image: url(:/newPrefix/accept.png);\n"
"background-color: rgb(230, 255, 221);")
        self.label_3.setText("")
        self.label_3.setObjectName("label_3")
        self.today = QtWidgets.QLabel(self.widget_2)
        self.today.setGeometry(QtCore.QRect(30, 80, 111, 31))
        font = QtGui.QFont()
        font.setFamily("DejaVu Sans")
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.today.setFont(font)
        self.today.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.today.setObjectName("today")
        self.label_10.raise_()
        self.main_frame_2.raise_()
        self.main_frame.raise_()
        self.label_11.raise_()
        self.label_12.raise_()
        self.label_13.raise_()
        self.label.raise_()
        self.date.raise_()
        self.success.raise_()
        self.pushButton.raise_()
        self.today.raise_()
        self.gridLayout.addWidget(self.widget_2, 0, 1, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.building.setText(_translate("MainWindow", "HUST D6"))
        self.QR.setText(_translate("MainWindow", "TextLabel"))
        self.date.setText(_translate("MainWindow", "ngày 10 tháng 11 năm 2022"))
        self.label_11.setText(_translate("MainWindow", "TRƯỜNG ĐẠI HỌC BÁCH KHOA HÀ NỘI"))
        self.label_13.setText(_translate("MainWindow", "HANOI UNIVERSITY OF SCIENCE AND TECHNOLOGY"))
        self.label_4.setText(_translate("MainWindow", "THAO TÁC THÀNH CÔNG !"))
        self.today.setText(_translate("MainWindow", "Chủ Nhật"))
import Images_rc
