# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'warning.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(800, 480)
        Dialog.setStyleSheet("background-color: rgba(238, 238, 236, 8);")
        self.gridLayout = QtWidgets.QGridLayout(Dialog)
        self.gridLayout.setObjectName("gridLayout")
        self.widget = QtWidgets.QWidget(Dialog)
        self.widget.setMinimumSize(QtCore.QSize(595, 0))
        self.widget.setMaximumSize(QtCore.QSize(595, 435))
        font = QtGui.QFont()
        font.setFamily("DejaVu Sans")
        font.setBold(False)
        font.setWeight(50)
        self.widget.setFont(font)
        self.widget.setStyleSheet("border-radius:25px;\n"
"background-color: rgb(227, 227, 227);")
        self.widget.setObjectName("widget")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.widget)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.widget_2 = QtWidgets.QWidget(self.widget)
        self.widget_2.setMaximumSize(QtCore.QSize(299, 16777215))
        self.widget_2.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border-radius: 20px")
        self.widget_2.setObjectName("widget_2")
        self.icon = QtWidgets.QLabel(self.widget_2)
        self.icon.setGeometry(QtCore.QRect(20, 80, 41, 31))
        self.icon.setStyleSheet("image: url(:/newPrefix/alert.png);")
        self.icon.setText("")
        self.icon.setObjectName("icon")
        self.Label = QtWidgets.QLabel(self.widget_2)
        self.Label.setGeometry(QtCore.QRect(70, 80, 141, 31))
        font = QtGui.QFont()
        font.setFamily("DejaVu Sans")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.Label.setFont(font)
        self.Label.setStyleSheet("color: rgb(192, 32, 52);")
        self.Label.setObjectName("Label")
        self.warning = QtWidgets.QTextBrowser(self.widget_2)
        self.warning.setGeometry(QtCore.QRect(10, 130, 271, 71))
        font = QtGui.QFont()
        font.setFamily("DejaVu Sans")
        font.setPointSize(12)
        self.warning.setFont(font)
        self.warning.setStyleSheet("border-radius: 0px;\n"
"color: rgb(164, 0, 0);")
        self.warning.setObjectName("warning")
        self.compen_cb = QtWidgets.QCheckBox(self.widget_2)
        self.compen_cb.setGeometry(QtCore.QRect(30, 230, 20, 20))
        font = QtGui.QFont()
        font.setFamily("DejaVu Sans")
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.compen_cb.setFont(font)
        self.compen_cb.setAutoFillBackground(False)
        self.compen_cb.setStyleSheet("QCheckBox::indicator {\n"
"    color: rgb(255, 255, 255);\n"
"     width: 20px;\n"
"     height: 20px;\n"
"}\n"
"")
        self.compen_cb.setObjectName("compen_cb")
        self.compensation = QtWidgets.QPushButton(self.widget_2)
        self.compensation.setGeometry(QtCore.QRect(10, 210, 281, 61))
        self.compensation.setMaximumSize(QtCore.QSize(16777215, 1000))
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.compensation.setFont(font)
        self.compensation.setStyleSheet("QPushButton {\n"
"   background-color: rgb(206, 22, 40 );\n"
"    color: rgb(255, 255, 255 );\n"
"   border-radius: 2px;\n"
"}\n"
"QPushButton:hover{\n"
"   background-color: rgb(226, 42, 60);\n"
"   color: rgb(255, 255, 255 );\n"
"    border-radius: 2px;\n"
"}\n"
"")
        self.compensation.setObjectName("compensation")
        self.instead = QtWidgets.QPushButton(self.widget_2)
        self.instead.setGeometry(QtCore.QRect(10, 280, 281, 61))
        self.instead.setMaximumSize(QtCore.QSize(16777215, 1000))
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.instead.setFont(font)
        self.instead.setStyleSheet("QPushButton {\n"
"   background-color: rgb(60, 60, 60);\n"
"    color: rgb(255, 255, 255 );\n"
"   border-radius: 2px;\n"
"}\n"
"QPushButton:hover{\n"
"   background-color: rgb(80, 80, 80);\n"
"   color: rgb(255, 255, 255 );\n"
"    border-radius: 2px;\n"
"}\n"
"")
        self.instead.setObjectName("instead")
        self.instead_cb = QtWidgets.QCheckBox(self.widget_2)
        self.instead_cb.setGeometry(QtCore.QRect(30, 300, 20, 20))
        font = QtGui.QFont()
        font.setFamily("DejaVu Sans")
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.instead_cb.setFont(font)
        self.instead_cb.setAutoFillBackground(False)
        self.instead_cb.setStyleSheet("QCheckBox::indicator {\n"
"    color: rgb(255, 255, 255);\n"
"     width: 20px;\n"
"     height: 20px;\n"
"}\n"
"")
        self.instead_cb.setObjectName("instead_cb")
        self.teacher = QtWidgets.QLabel(self.widget_2)
        self.teacher.setGeometry(QtCore.QRect(10, 345, 281, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.teacher.setFont(font)
        self.teacher.setStyleSheet("background-color: rgb(238, 238, 236);b")
        self.teacher.setAlignment(QtCore.Qt.AlignCenter)
        self.teacher.setObjectName("teacher")
        self.label_5 = QtWidgets.QLabel(self.widget_2)
        self.label_5.setGeometry(QtCore.QRect(0, -1, 299, 111))
        self.label_5.setStyleSheet("background-color: rgb(192, 32, 52 );\n"
"border-radius:20px;\n"
"")
        self.label_5.setText("")
        self.label_5.setObjectName("label_5")
        self.label_7 = QtWidgets.QLabel(self.widget_2)
        self.label_7.setGeometry(QtCore.QRect(0, 60, 299, 351))
        self.label_7.setStyleSheet("\n"
"border-radius:20px;\n"
"")
        self.label_7.setText("")
        self.label_7.setObjectName("label_7")
        self.main_frame_3 = QtWidgets.QLabel(self.widget_2)
        self.main_frame_3.setGeometry(QtCore.QRect(0, 55, 299, 250))
        self.main_frame_3.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"background-color: rgb(186, 189, 182);\n"
"border-radius: 20px")
        self.main_frame_3.setText("")
        self.main_frame_3.setObjectName("main_frame_3")
        self.building = QtWidgets.QPushButton(self.widget_2)
        self.building.setGeometry(QtCore.QRect(70, 15, 160, 30))
        font = QtGui.QFont()
        font.setFamily("DejaVu Sans")
        font.setPointSize(15)
        font.setBold(True)
        font.setUnderline(True)
        font.setWeight(75)
        self.building.setFont(font)
        self.building.setStyleSheet("color: rgb(255, 255, 255);\n"
"border-radius: 10px;\n"
"background-color: rgb(192, 32, 52 );")
        self.building.setObjectName("building")
        self.back = QtWidgets.QPushButton(self.widget_2)
        self.back.setGeometry(QtCore.QRect(20, 15, 21, 31))
        self.back.setStyleSheet("border-radius: 25px;\n"
"image: url(:/newPrefix/previous.png);\n"
"background-color: rgb(192, 32, 52 );\n"
"")
        self.back.setText("")
        self.back.setObjectName("back")
        self.label_5.raise_()
        self.main_frame_3.raise_()
        self.label_7.raise_()
        self.icon.raise_()
        self.Label.raise_()
        self.warning.raise_()
        self.compensation.raise_()
        self.compen_cb.raise_()
        self.teacher.raise_()
        self.instead.raise_()
        self.instead_cb.raise_()
        self.building.raise_()
        self.back.raise_()
        self.gridLayout_2.addWidget(self.widget_2, 0, 1, 1, 1)
        self.widget_3 = QtWidgets.QWidget(self.widget)
        self.widget_3.setMaximumSize(QtCore.QSize(259, 2000))
        self.widget_3.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border-radius: 20px")
        self.widget_3.setObjectName("widget_3")
        self.label_8 = QtWidgets.QLabel(self.widget_3)
        self.label_8.setGeometry(QtCore.QRect(0, -1, 259, 111))
        self.label_8.setStyleSheet("background-color: rgb(192, 32, 52 );\n"
"border-radius:20px;\n"
"")
        self.label_8.setText("")
        self.label_8.setObjectName("label_8")
        self.label_9 = QtWidgets.QLabel(self.widget_3)
        self.label_9.setGeometry(QtCore.QRect(0, 60, 259, 351))
        self.label_9.setStyleSheet("\n"
"border-radius:20px;\n"
"")
        self.label_9.setText("")
        self.label_9.setObjectName("label_9")
        self.widget_4 = QtWidgets.QWidget(self.widget_3)
        self.widget_4.setGeometry(QtCore.QRect(0, 60, 259, 351))
        self.widget_4.setMaximumSize(QtCore.QSize(259, 2000))
        self.widget_4.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border-radius: 20px")
        self.widget_4.setObjectName("widget_4")
        self.nine = QtWidgets.QPushButton(self.widget_4)
        self.nine.setGeometry(QtCore.QRect(180, 110, 71, 50))
        self.nine.setMaximumSize(QtCore.QSize(16777215, 50))
        font = QtGui.QFont()
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.nine.setFont(font)
        self.nine.setStyleSheet("QPushButton {\n"
"   background-color: rgb(245, 245, 245);\n"
"color: rgb(70, 70, 70);\n"
"border-radius: 3px;\n"
"}\n"
"QPushButton:hover{\n"
"   background-color: rgb(225, 225, 225);\n"
"color: rgb(70, 70, 70);\n"
"border-radius: 3px;\n"
"}")
        self.nine.setObjectName("nine")
        self.room = QtWidgets.QLabel(self.widget_4)
        self.room.setGeometry(QtCore.QRect(10, 60, 161, 41))
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.room.setFont(font)
        self.room.setStyleSheet("background-color: rgb(238, 238, 236);")
        self.room.setAlignment(QtCore.Qt.AlignCenter)
        self.room.setObjectName("room")
        self.six = QtWidgets.QPushButton(self.widget_4)
        self.six.setGeometry(QtCore.QRect(180, 170, 71, 50))
        self.six.setMaximumSize(QtCore.QSize(16777215, 50))
        font = QtGui.QFont()
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.six.setFont(font)
        self.six.setStyleSheet("QPushButton {\n"
"   background-color: rgb(245, 245, 245);\n"
"color: rgb(70, 70, 70);\n"
"border-radius: 3px;\n"
"}\n"
"QPushButton:hover{\n"
"   background-color: rgb(225, 225, 225);\n"
"color: rgb(70, 70, 70);\n"
"border-radius: 3px;\n"
"}")
        self.six.setObjectName("six")
        self.one = QtWidgets.QPushButton(self.widget_4)
        self.one.setGeometry(QtCore.QRect(9, 228, 71, 50))
        self.one.setMaximumSize(QtCore.QSize(16777215, 50))
        font = QtGui.QFont()
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.one.setFont(font)
        self.one.setStyleSheet("QPushButton {\n"
"   background-color: rgb(245, 245, 245);\n"
"color: rgb(70, 70, 70);\n"
"border-radius: 3px;\n"
"}\n"
"QPushButton:hover{\n"
"   background-color: rgb(225, 225, 225);\n"
"color: rgb(70, 70, 70);\n"
"border-radius: 3px;\n"
"}")
        self.one.setObjectName("one")
        self.three = QtWidgets.QPushButton(self.widget_4)
        self.three.setGeometry(QtCore.QRect(180, 230, 71, 50))
        self.three.setMaximumSize(QtCore.QSize(16777215, 50))
        font = QtGui.QFont()
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.three.setFont(font)
        self.three.setStyleSheet("QPushButton {\n"
"   background-color: rgb(245, 245, 245);\n"
"color: rgb(70, 70, 70);\n"
"border-radius: 3px;\n"
"}\n"
"QPushButton:hover{\n"
"   background-color: rgb(225, 225, 225);\n"
"color: rgb(70, 70, 70);\n"
"border-radius: 3px;\n"
"}")
        self.three.setObjectName("three")
        self.eight = QtWidgets.QPushButton(self.widget_4)
        self.eight.setGeometry(QtCore.QRect(90, 110, 81, 50))
        self.eight.setMaximumSize(QtCore.QSize(16777215, 50))
        font = QtGui.QFont()
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.eight.setFont(font)
        self.eight.setStyleSheet("QPushButton {\n"
"   background-color: rgb(245, 245, 245);\n"
"color: rgb(70, 70, 70);\n"
"border-radius: 3px;\n"
"}\n"
"QPushButton:hover{\n"
"   background-color: rgb(225, 225, 225);\n"
"color: rgb(70, 70, 70);\n"
"border-radius: 3px;\n"
"}")
        self.eight.setObjectName("eight")
        self.Del = QtWidgets.QPushButton(self.widget_4)
        self.Del.setGeometry(QtCore.QRect(180, 60, 71, 40))
        self.Del.setMaximumSize(QtCore.QSize(16777215, 40))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.Del.setFont(font)
        self.Del.setStyleSheet("background-color: rgb(70, 70, 70);\n"
"color: rgb(245, 245, 245);\n"
"border-radius: 3px;")
        self.Del.setObjectName("Del")
        self.four = QtWidgets.QPushButton(self.widget_4)
        self.four.setGeometry(QtCore.QRect(9, 171, 71, 50))
        self.four.setMaximumSize(QtCore.QSize(16777215, 50))
        font = QtGui.QFont()
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.four.setFont(font)
        self.four.setStyleSheet("QPushButton {\n"
"   background-color: rgb(245, 245, 245);\n"
"color: rgb(70, 70, 70);\n"
"border-radius: 3px;\n"
"}\n"
"QPushButton:hover{\n"
"   background-color: rgb(225, 225, 225);\n"
"color: rgb(70, 70, 70);\n"
"border-radius: 3px;\n"
"}")
        self.four.setObjectName("four")
        self.seven = QtWidgets.QPushButton(self.widget_4)
        self.seven.setGeometry(QtCore.QRect(10, 110, 71, 50))
        self.seven.setMaximumSize(QtCore.QSize(16777215, 50))
        font = QtGui.QFont()
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.seven.setFont(font)
        self.seven.setStyleSheet("QPushButton {\n"
"   background-color: rgb(245, 245, 245);\n"
"color: rgb(70, 70, 70);\n"
"border-radius: 3px;\n"
"}\n"
"QPushButton:hover{\n"
"   background-color: rgb(225, 225, 225);\n"
"color: rgb(70, 70, 70);\n"
"border-radius: 3px;\n"
"}\n"
"")
        self.seven.setObjectName("seven")
        self.five = QtWidgets.QPushButton(self.widget_4)
        self.five.setGeometry(QtCore.QRect(91, 171, 81, 50))
        self.five.setMaximumSize(QtCore.QSize(16777215, 50))
        font = QtGui.QFont()
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.five.setFont(font)
        self.five.setStyleSheet("QPushButton {\n"
"   background-color: rgb(245, 245, 245);\n"
"color: rgb(70, 70, 70);\n"
"border-radius: 3px;\n"
"}\n"
"QPushButton:hover{\n"
"   background-color: rgb(225, 225, 225);\n"
"color: rgb(70, 70, 70);\n"
"border-radius: 3px;\n"
"}")
        self.five.setObjectName("five")
        self.two = QtWidgets.QPushButton(self.widget_4)
        self.two.setGeometry(QtCore.QRect(91, 228, 81, 50))
        self.two.setMaximumSize(QtCore.QSize(16777215, 50))
        font = QtGui.QFont()
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.two.setFont(font)
        self.two.setStyleSheet("QPushButton {\n"
"   background-color: rgb(245, 245, 245);\n"
"color: rgb(70, 70, 70);\n"
"border-radius: 3px;\n"
"}\n"
"QPushButton:hover{\n"
"   background-color: rgb(225, 225, 225);\n"
"color: rgb(70, 70, 70);\n"
"border-radius: 3px;\n"
"}")
        self.two.setObjectName("two")
        self.label_2 = QtWidgets.QLabel(self.widget_4)
        self.label_2.setGeometry(QtCore.QRect(9, 10, 238, 50))
        self.label_2.setMinimumSize(QtCore.QSize(0, 50))
        self.label_2.setMaximumSize(QtCore.QSize(16777215, 50))
        font = QtGui.QFont()
        font.setFamily("DejaVu Sans")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.zero = QtWidgets.QPushButton(self.widget_4)
        self.zero.setGeometry(QtCore.QRect(9, 285, 71, 50))
        self.zero.setMaximumSize(QtCore.QSize(16777215, 50))
        font = QtGui.QFont()
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.zero.setFont(font)
        self.zero.setStyleSheet("QPushButton {\n"
"   background-color: rgb(245, 245, 245);\n"
"color: rgb(70, 70, 70);\n"
"border-radius: 3px;\n"
"}\n"
"QPushButton:hover{\n"
"   background-color: rgb(225, 225, 225);\n"
"color: rgb(70, 70, 70);\n"
"border-radius: 3px;\n"
"}")
        self.zero.setObjectName("zero")
        self.OK = QtWidgets.QPushButton(self.widget_4)
        self.OK.setGeometry(QtCore.QRect(91, 285, 161, 50))
        self.OK.setMaximumSize(QtCore.QSize(16777215, 50))
        font = QtGui.QFont()
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.OK.setFont(font)
        self.OK.setStyleSheet("\n"
"QPushButton {\n"
"   background-color: rgb(192, 32, 52 );\n"
"color: rgb(255, 255, 255);\n"
"border-radius: 3px;\n"
"}\n"
"QPushButton:hover{\n"
"   background-color: rgb(222, 45, 65 );\n"
"color: rgb(255, 255, 255);\n"
"border-radius: 3px;\n"
"}")
        self.OK.setObjectName("OK")
        self.main_frame_4 = QtWidgets.QLabel(self.widget_3)
        self.main_frame_4.setGeometry(QtCore.QRect(0, 55, 259, 250))
        self.main_frame_4.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"background-color: rgb(186, 189, 182);\n"
"border-radius: 20px")
        self.main_frame_4.setText("")
        self.main_frame_4.setObjectName("main_frame_4")
        self.label_8.raise_()
        self.main_frame_4.raise_()
        self.label_9.raise_()
        self.widget_4.raise_()
        self.gridLayout_2.addWidget(self.widget_3, 0, 2, 1, 1)
        self.gridLayout.addWidget(self.widget, 0, 1, 1, 1)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.Label.setText(_translate("Dialog", "CẢNH BÁO!"))
        self.warning.setHtml(_translate("Dialog", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'DejaVu Sans\'; font-size:12pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"justify\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Ubuntu\';\">Hiện tại không có tiết dạy nào cả, thầy cô vui lòng chọn một trong các lý do sau để tiếp tục mượn thiết bị.</span></p></body></html>"))
        self.compen_cb.setText(_translate("Dialog", "     Điều khiển điều hòa"))
        self.compensation.setText(_translate("Dialog", "DẠY BÙ"))
        self.instead.setText(_translate("Dialog", "DẠY THAY"))
        self.instead_cb.setText(_translate("Dialog", "     Điều khiển điều hòa"))
        self.teacher.setText(_translate("Dialog", "GV: TRƯƠNG ĐỨC PHỨC"))
        self.building.setText(_translate("Dialog", "HUST D6"))
        self.nine.setText(_translate("Dialog", "9"))
        self.room.setText(_translate("Dialog", "302"))
        self.six.setText(_translate("Dialog", "6"))
        self.one.setText(_translate("Dialog", "1"))
        self.three.setText(_translate("Dialog", "3"))
        self.eight.setText(_translate("Dialog", "8"))
        self.Del.setText(_translate("Dialog", "Del"))
        self.four.setText(_translate("Dialog", "4"))
        self.seven.setText(_translate("Dialog", "7"))
        self.five.setText(_translate("Dialog", "5"))
        self.two.setText(_translate("Dialog", "2"))
        self.label_2.setText(_translate("Dialog", "MỜI THẦY CÔ NHẬP PHÒNG HỌC"))
        self.zero.setText(_translate("Dialog", "0"))
        self.OK.setText(_translate("Dialog", "OK"))
import Images_rc
